### ISSUE TITLE
port is not accepted 

### ISSUE THREAD

**Issue by naja7host** [CpuID/pve2-api-php-client#13]
when i call the class i get 

Uncaught exception 'PVE2_Exception' with message 'Port must be an integer between 1 and 65535.'

my code is 

include("pve2_api.class.php");	
$pve2 = new PVE2_API($hostname, $user , $realm ,  $pasword  , $port);

when i remove port it work perfectly . because the class has the port 8006 if empty . 

the case here is because the port is saved in database as a string , what we should do is convert it in intiger 

(int)$port .

so i think is better to update the README file to include the HOWTO , or remove

**Comment by danhunsaker** [comment]
It needs to be an integer - remove the quotes.

**Comment by danhunsaker** [comment]
We may be able to remove the `is_int()`...  Thoughts, @CpuID?

**Comment by naja7host** [comment]
the case here is because the port is saved in database as a string , what we should do is convert it in intiger

(int)$port .

so i think is better to update the README file to include the HOWTO , or remove

**Comment by danhunsaker** [comment]
How about we switch to `filter_var()`?  PR incoming for comments.

**Comment by danhunsaker** [comment]
PR accepted.  So if it doesn't work, please reopen!
