### ISSUE TITLE
Support for /png/ 

### ISSUE THREAD

**Issue by antoiner77** [CpuID/pve2-api-php-client#15]
It would be a good idea to add  the support of rrd graph (with /png/ instead of /Json/)

**Comment by texh** [comment]
Uh, maybe too little too late but I added this to a for a while back - never created a pull request though and now they can't be automerged :(..

The code's at the following if anyone dare try to make this work https://github.com/texh/pve2-api-php-client/commit/73f9595ad91314ccd91300e65c57aad495f64fac

**Comment by danhunsaker** [comment]
Might be able to rebase this...

**Comment by ktb92677** [comment]
Any updates here? Is there a way I can implement this easily?

**Comment by lsthompson** [comment]
It's possible to make this work as-is, and the linked commit/repo is dead in the water now. Closing. :-)
