### ISSUE TITLE
PHP Fatal error:  Call to undefined method PVE2_API::constructor_success()

### ISSUE THREAD

**Issue by whoim2** [CpuID/pve2-api-php-client#17]
Have this error..
[code]
<?php
...
require('proxmox.api.php'); //copy of pve2_api.class.php
..
$pve2 = new PVE2_API($pve_nodes[$pve_node]['ip'], $pve_nodes[$pve_node]['user'], $pve_nodes[$pve_node]['auth_type'], $pve_nodes[$pve_node]['password'], 8006, false);
..
$pve2->constructor_success()) {
        /* Optional - enable debugging. It print()'s any results currently */
        $pve2->set_debug(true);

        if ($pve2->login()) {
            foreach ($pve2->get_node_list() as $node_name) {
                print_r($pve2->get("/nodes/".$pve_node."/status"));
            }
        } else {
            print("Login to Proxmox Host failed.\n");
            exit;
        }
    } else {
        print("Could not create PVE2_API object.\n");
        exit;
    }
... 
?>
[/code]

php -v
PHP 5.4.43 (cli) (built: Jul 11 2015 00:05:29)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
OS: CentOS 6.5 i386

**Comment by danhunsaker** [comment]
This function was removed in favor of throwing an exception if the constructor fails.  You'll need to update your code accordingly.

**Comment by whoim2** [comment]
i see your file "README.MD" for example..

**Comment by naja7host** [comment]
The read me file should be updated . to avoid this case .

Naja7Host Inc
p: 0539.71.42.32 (fixe)
G: 0665. 173 448 (Gsm)
G: 0674. 823 870 (Gsm)
F: 0539.71.42.32 (Fax)
w: www.naja7host.com
-------------------------
Support : support@naja7host.com
Relation Clientèles : naja7host@naja7host.com
Service Commercial : sales@naja7host.com

2015-07-20 16:04 GMT+01:00 whoim2 <notifications@github.com>:

**Comment by naja7host** [comment]
Update the README file as soon as possible, having exemple with the worng function in the class has no sense .

**Comment by danhunsaker** [comment]
You are more than welcome to submit a PR for this.

**Comment by CpuID** [comment]
https://github.com/CpuID/pve2-api-php-client/blob/master/README.md updated in master, sorry about that.

**Comment by naja7host** [comment]
$pve2->set_debug(true); is no longer used too .
