### ISSUE TITLE
issue while creating vm

### ISSUE THREAD

**Issue by avi123nash** [CpuID/pve2-api-php-client#20]
I am trying to use your api...But i'm facing a problem here...when i try to create a vm in proxmox, the vm could not be created....when i check the logs it showed me 

error 500 no options specified....

Can you please help me out...:)

**Comment by CpuID** [comment]
Do you have a valid $parameters variable being specified for the post() method?

Also, what $action_path are you hitting with your request?

**Comment by avi123nash** [comment]
yes i have used an array containing all the options required for creating an openvz container like ostemplate, cpu cores, cpu units and other related info wait i'll show it to you here:

		$new_container_settings = array();
		$new_container_settings['ostemplate'] = "local:vztmpl/".$container_settings['ostemplate'];
		$new_container_settings['vmid'] = 'vps_id';
		$new_container_settings['hostname'] = 'hostname';
		$new_container_settings['storage'] = "local";
		$new_container_settings['memory'] = 'ram';
		$new_container_settings['swap'] = 'swap memory';
		$new_container_settings['disk'] = $diskspace;
		$new_container_settings['cpus'] = 'cores';
		$new_container_settings['ip_address'] = 'ip_address';
		$new_container_settings['description'] = "Test VM using Proxmox 2.0 API";		
		$new_container_settings['cpuunits'] = 'cpu';	
		$new_container_settings['nameserver'] = $container_settings['nameserver'];

and the action path for creating the vm is given below in the post method:

$ret = $pve2->post("/nodes/pve/openvz", $new_container_settings);

Am i doing something wrong?

Thanks...:)

**Comment by CpuID** [comment]
What version of Proxmox are you running? I don't use Proxmox on a day-to-day basis myself anymore, but noticed this: https://www.turnkeylinux.org/forum/support/20150504/proxmox-moving-openvz-lxc

**Comment by avi123nash** [comment]
I am using proxmox versin 3.4...Showing you the version details

root@pve:~# pveversion -v
proxmox-ve-2.6.32: 3.4-156 (running kernel: 2.6.32-39-pve)
pve-manager: 3.4-6 (running version: 3.4-6/102d4547)
pve-kernel-2.6.32-39-pve: 2.6.32-156
lvm2: 2.02.98-pve4
clvm: 2.02.98-pve4
corosync-pve: 1.4.7-1
openais-pve: 1.1.4-3
libqb0: 0.11.1-2
redhat-cluster-pve: 3.2.0-2
resource-agents-pve: 3.9.2-4
fence-agents-pve: 4.0.10-2
pve-cluster: 3.0-17
qemu-server: 3.4-6
pve-firmware: 1.1-4
libpve-common-perl: 3.0-24
libpve-access-control: 3.0-16
libpve-storage-perl: 3.0-33
pve-libspice-server1: 0.12.4-3
vncterm: 1.1-8
vzctl: 4.0-1pve6
vzprocps: 2.0.11-2
vzquota: 3.1-2
pve-qemu-kvm: 2.2-10
ksm-control-daemon: 1.1-1
glusterfs-client: 3.5.2-1

**Comment by CpuID** [comment]
OK doesn't sound like thats the issue (the roadmap page claims 4.0 is when they cutover from OpenVZ to LXC). Any hints in the Proxmox logs? I can't think of anything obvious here, sorry.

**Comment by avi123nash** [comment]
Oh yeah i'm really sorry i didn't tell you ..The data array shows null...here is a part of the log.
Headers:

HTTP/1.1 500 no options specified
Cache-Control: max-age=0
Connection: close
Date: Tue, 15 Dec 2015 08:33:10 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0
Content-Length: 13
Content-Type: application/json;charset=UTF-8
Expires: Tue, 15 Dec 2015 08:33:10 GMT

End Headers

Data:

{"data":null}

End Data

RESPONSE ARRAY:

array (
  'data' => NULL,
)

END RESPONSE ARRAY
----------------------------------------------
This API Request Failed.
HTTP Response - 500
HTTP Error - HTTP/1.1 500 no options specified

is it that the data is not being passed to proxmox?

**Comment by avi123nash** [comment]
Thanks for your help..by the way...appreciated...:)
