### ISSUE TITLE
Update root password in LXC container

### ISSUE THREAD

**Issue by BenJaziaSadok** [CpuID/pve2-api-php-client#22]
I can set a root password when creating a container using the API, but, i can't find a method to update this password. 
Otherwise, i will use ssh commands

**Comment by naja7host** [comment]
this method is not supported via API .

**Comment by danhunsaker** [comment]
Yes, the API (and by extension, the web interface) does not support changing the root password after container creation.  This must be done via SSH directly into the guest system.
