### ISSUE TITLE
Clone KVM Template

### ISSUE THREAD

**Issue by dfrankes** [CpuID/pve2-api-php-client#24]
Hi There!

I'm trying to clone a KVM template (template id: 100) This is the code i made but the only output im getting is "boolean false"

![image](https://cloud.githubusercontent.com/assets/7813606/12418242/6f041b5e-beae-11e5-99bf-1c762f5ef25f.png)

![image](https://cloud.githubusercontent.com/assets/7813606/12418247/7335c48e-beae-11e5-9c63-643739ac4cb0.png)

**Comment by danhunsaker** [comment]
What do you get when you try to run the same request using pvesh?  The code itself looks correct, but the API is outside this project's scope.

**Comment by dfrankes** [comment]
I will try that out in a bit, But the wierd part is, It doesnt give any error output.

**Comment by danhunsaker** [comment]
Well, to be fair, the client lib doesn't actually do much more than handle authentication on each request.  Otherwise, it's basically just a cURL wrapper.  So it won't actually provide error details on most things.

**Comment by dfrankes** [comment]
I understand, But its retarded that promox doesnt output any errors.

**Comment by danhunsaker** [comment]
The PVE2 API probably does, actually.  The client lib simply doesn't report them.

**Comment by ChrysUk** [comment]
Hy guys ,did you finder any infos about this ?  Thank you

**Comment by lucapiccio** [comment]
The last commit as added the function : clone_vm ($node,$vmid) 

Hope this can help to solve your problem.

**Comment by lsthompson** [comment]
Thanks @lucapiccio - closing this as completed! :-)
