### ISSUE TITLE
Setting disk capacity on CT creation

### ISSUE THREAD

**Issue by BenJaziaSadok** [CpuID/pve2-api-php-client#26]
I'm using the api for creating LXC container.
When i set rootfs to choose the storage disk and it's size like this
$new_container_settings['rootfs']=local:112/vm-112-disk-1.raw,size=40
I get a container created but the root disk appear to be empty in proxmox admin console
Note that when i create a container with the admin interface i get the same parameter just like as i wrote in the API.
Are there a missing parameter or a configuration to do?
$new_container_settings['disk'] no longer works on PVE 4.1

**Comment by danhunsaker** [comment]
This appears to be an issue in the scope of Proxmox itself.  Have you asked this question on the forums or mailing list?

**Comment by danhunsaker** [comment]
For the record, `disk` is now `rootfs` in PVE 4.1.  Still outside the scope of this project, but it's an answer.
