### ISSUE TITLE
Suddenly login always fails whereas nothing changed in the code : Howto solve

### ISSUE THREAD

**Issue by julienmary** [CpuID/pve2-api-php-client#28]
Well, this is not a bug report but more about unexpected behavior.

Proxmox by default has SSL certificates which are binded to the ip address. If you install proper domain certificate name aka : myballs.mydomain.com to let VPS users login and access console in a green fashion, login with the IP address stops to work.

In the code you have to replace $hostname by the FQDN. Then login works again.

A solid code to keep login in case of change would be : 

```
function promox_get_pve2_connection($fqdn,$ip,$password) {
  $pve2 = new PVE2_API($fqdn, "root", "pam", $password);
  if ($pve2->login()) {
    return $pve2;
  }
  else { // We try with IP address
    $pve2 = new PVE2_API($ip, "root", "pam", $password);
    if ($pve2->login()) {
      return $pve2;
    }
    else { // We are really dead
      print("Login to Proxmox Host failed.\n");
    }
  }
}
```

**Comment by danhunsaker** [comment]
Another option is to include the IP address in the `SubjectAlternativeNames` section of the certificate.  The exact process for doing that varies somewhat from issuer to issuer (and unfortunately, some - such as Let's Encrypt - don't allow it at all).
