### ISSUE TITLE
Create VM via API complains that {vmid}.conf file is not existing

### ISSUE THREAD

**Issue by julienmary** [CpuID/pve2-api-php-client#29]
The error message is :
`PHP message: This API Request Failed. 
HTTP Response - 500 
HTTP Error - HTTP/1.1 500 Configuration file 'nodes/teleonomy-1/qemu-server/103.conf' does not exist" while reading response header from upstream, client: 192.168.1.8, server: dev.teleonomy.net, request: "POST /devel/php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "dev.teleonomy.net", referrer: "http://dev.teleonomy.net/devel/php" `

By command line, it works : 
pvesh create /nodes/teleonomy-1/qemu -memory 8192 -sockets 2 -cores 2 -net0 virtio,bridge=vmbr0 -net1 virtio,bridge=vmbr1 -vmid 103 -ostype l26 -virtio0 media=disk,volume=local:103/vm-103-disk-1.qcow2

That gets 200Ok.
But via API, no.
The settings array can be be seen at : https://www.teleonomy.net/sites/default/files/settings.png

The POSTing URL via API is : /nodes/teleonomy-1/qemu/103/config

I have spent 8 hours on this, and cannot find WTF is wrong ...

**Comment by danhunsaker** [comment]
You can't send requests to items that don't yet exist. The API endpoint you want is always identical to the path used with `pvesh` - in this case, you want to POST to `/nodes/teleonomy-1/qemu`.

**Comment by julienmary** [comment]
Thank you so much !!!! I wake up, see if I have a reply. Yes ! I just added the settings['vmid'] in my array, changed the path as you mentioned ... and it worked right away.

**Comment by danhunsaker** [comment]
No problem. 😊
