### ISSUE TITLE
VM Shutdown and start - POST Proccess

### ISSUE THREAD

**Issue by emresaracoglu** [CpuID/pve2-api-php-client#31]
Hello,

I can't run my code, can you tell where you made a mistake?

```
public function post_vm_acKapat($nodeIsmi, $vmID,$paracik)
		{
			
			$gosteramcana = $this->post("/nodes/$nodeIsmi/qemu/$vmID/status/start", $paracik);
			if ($gosteramcana == null) {
				return false;
			} else {
				echo "VM is starting.";
			}
		}
```

```
if ($pve2->login()) {
		$paraciks = array(
			"node" => "prox",
			"vmid" => "104"
		);
		$pve2->post_vm_acKapat('prox', 104, $paraciks);
	} else {
		print("Login to Proxmox Host failed.\n");
		exit;
	}
```

I spent 3 hours but.. 
Also, thank you for this project.

**Comment by danhunsaker** [comment]
I believe the confusion, here, is that the PVE2 docs don't separate URL parameters from body parameters very well. The way to fix this code is probably to simply use `null` as the parameters argument, since both `node` and `vmid` are already passed in the URL.

**Comment by emresaracoglu** [comment]
```
$paraciks = array(
			"node" => "null",
			"vmid" => "null"
		);
```

Like this? - I tried this but it did not change. Do you have a chance to show an example for me?
Thank you

**Comment by danhunsaker** [comment]
No, as in `$paraciks = null;`. You need to pass nothing at all in the request body.

**Comment by emresaracoglu** [comment]
Worked. Daniel, you are great! Could be this apply to cloning?

```
$paraciks = array(
	"newid" => "110",
	"vmid" => "104",
	"node" => "prox"
);
$pve2->post_vm_cloneOlusturma('prox', '104', $paraciks);
###
$this->post("/nodes/$nodeIsmi/qemu/$vmID/clone", $paracik);
```

**Comment by danhunsaker** [comment]
Partially. Anything that's in the URL needs to be completely left out of the body. So the only key you should have in the clone's `$paraciks` should be the `newid` - the `node` and `vmid` are already in the URL.

**Comment by emresaracoglu** [comment]
I thought so too but did not work. there's no mistake and action.

```
$paraciks = array(
	"newid" => "110"
);
```

**Comment by emresaracoglu** [comment]
If Debug is active, I getting this error:

`Fatal error: Uncaught Error: Call to undefined method PVE2_API::set_debug() in ... `

**Comment by danhunsaker** [comment]
Right, we switched to sending output to the error log instead, and removed the `set_debug()` method. That's why I edited my comment to say to check the log instead.

**Comment by emresaracoglu** [comment]
```
[26-Nov-2017 21:24:40] This API Request Failed.
HTTP Response - 500
HTTP Error - HTTP/1.1 500 Linked clone feature is not supported for drive 'scsi0'
```
I guess I can not perform the cloning process because it does not support it.

**Comment by emresaracoglu** [comment]
I solved, VM to template :)
Daniel, **thank you for your help.**
