### ISSUE TITLE
add a node to cluster

### ISSUE THREAD

**Issue by fatemehgholampour** [CpuID/pve2-api-php-client#33]
after login I use this url  /api2/json/cluster/config/nodes/{node}  to POST a node
and it return:

POST /cluster/config/nodes/' not implemented

my version is up to date and is 5.2

**Comment by danhunsaker** [comment]
Is that the right endpoint? It doesn't look quite right, but I don't recall, at the moment off the top of my head, which it would be. At the least, I suspect `config` shouldn't be in that URL...

**Comment by fatemehgholampour** [comment]
I found out my problem the right URL is  /api2/json/cluster/config/nodes/yourNodeName
so I close this issue
