### ISSUE TITLE
$pve2->get request

### ISSUE THREAD

**Issue by proxene** [CpuID/pve2-api-php-client#34]
Hi, I have a problem with get request.
I try to create a vnc iframe and when I send the request I get this result : bool(false).

`$pve2->login();

        if ($pve2->login()) {
            
            $config = $pve2->post("/nodes/test/lxc/100/vncproxy", array()); 
            
            $websocket = $pve2->get("/nodes/test/lxc/100/vncwebsocket",
            [
                'port' => $config['data']['port'],
                'vncticket' => $config['data']['ticket']
            ]);

        } else {
            
            print("Login to Proxmox Host failed.\n");
            exit;
            
        }`

Can you help me ?
Thank you

Best regards,
Proxene

**Comment by lsthompson** [comment]
Hi, this would be better suited to the [Proxmox Forums](https://forum.proxmox.com/).

Please raise a thread there if you still have issues. VNC proxying can be quite particular.
