### ISSUE TITLE
Printing "FULL REPONSE" every time

### ISSUE THREAD

**Issue by GrabauNetwork** [CpuID/pve2-api-php-client#45]
Hi, I think you forgot to delete / comment line 233-238 because at every (get, put, post delete) action the script returns an full response from curl.

![image](https://github.com/CpuID/pve2-api-php-client/assets/108761203/85b391f8-b180-4d99-b1c6-eea3e1dc0f08)

**Comment by lsthompson** [comment]
Thanks for this, waiting for 2nd review of Pull #49 to merge, then will look to add a verbose option via #47 in 2024.
