### ISSUE TITLE
"Common Tasks" mentioned in TODO

### ISSUE THREAD

**Issue by danhunsaker** [CpuID/pve2-api-php-client#5]
This isn't an issue, per se, so much as an inquiry.  What tasks would be considered common/useful enough to provide such wrappers for?  I'd be happy to implement this child class, but I need to know what I'd be writing to do it.  Listed in the TODO already are:

* Create VM
* Create container
* Change container settings

I can assume that I should also add (as it's implied)

* Change VM settings

But what else should be supported?

**Comment by CpuID** [comment]
Cool :)
